[[sources]]
title = "Rust Book 2nd edition"
base_url = "https://doc.rust-lang.org/book"
directory = "mdbooks/book/src/"

[[sources]]
title = "Rust Book 1st edition"
base_url = "https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition"
directory = "mdbooks/book/first-edition/src/"

[[sources]]
title = "Comprehensive Rust"
base_url = "https://google.github.io/comprehensive-rust"
directory = "mdbooks/comprehensive-rust/src/"

[[sources]]
title = "Rust By Example"
base_url = "https://doc.rust-lang.org/rust-by-example"
directory = "mdbooks/rust-by-example/src"

[[sources]]
title = "Rust vs Python"
base_url = "https://alice-bob.dev"
directory = "mdbooks/rust-vs-python/src"
